# Generated by Django 4.2 on 2023-04-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_status_name_task_description_task_status_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='statusId',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='todo.status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=64),
        ),
    ]
